sudo: required
language: node_js
branches:
  only:
  - master
matrix:
  include:
    - node_js: "10"
    - node_js: "12"
      if: head_branch IS blank AND branch = master
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
    - lantern-data
    - /home/travis/.rvm/gems/
install:
  # if our e2e tests fail in the future it might be that we are not compatible
  # with the latest puppeteer api so we probably need to run on chromimum
  # @see https://github.com/GoogleChrome/lighthouse/pull/4640/files#r171425004
  - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
  - yarn --frozen-lockfile
before_script:
  - export DISPLAY=:99.0
  # see comment above about puppeteer
  - export CHROME_PATH="$(which google-chrome-stable)"
  - sh -e /etc/init.d/xvfb start
  # Print out the Chrome version so we know what we're working with
  - google-chrome-stable --version
  - yarn build-all
script:
  - yarn bundlesize
  - yarn diff:sample-json
  - yarn lint
  - yarn unit:cicoverage
  - yarn type-check
  - yarn smoke:cicoverage
  - yarn test-clients
  - yarn test-viewer
  - yarn test-lantern
  - yarn i18n:checks
before_cache:
  # nyc, jest and other projects store files in here. They mess up the travis build cache.
  - rm -rf ./node_modules/.cache/
after_success:
  - yarn coveralls
  - yarn codecov
addons:
  chrome: stable
